# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bd117aee2d0f9236b5eae182c2f1f505c4a4aa058ad76d8d9505c060f0a05de044798c3c892b6e51b150dec406f160d3b61fe27abcc6d4b05321307c089b7f2

test:
  secret_key_base: dce406032e34e650985bb1ee16c453555f7ae4e6850bc61acb3c102bb7aa33905879bdccfd99b9df87adabf9b30619baed8169d21e8e57757ce64e2998aaf864

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
